### ISSUE TITLE
Jumping back (like with ctags ctrl-t)

### ISSUE THREAD

**Issue by andynu** [kis9a/vimsidian#9]
Vimsidian is great! Thank you so much! I sometimes edit my obsidian files in vim, and being able to navigate the internal links is fantastic! I notice though that there is no go-back to the previous file command. While I can use e# to jump back to the immediately preceeding file, it only works once. 

I wanted to be able to dig into the internal links, and then back out of them similar to the way the ctags ctrl-]/ctrl-t commands work. To that end I generated a tags file of my obsidian files, and used your excellent vim function to select the appropriate part of the internal link.

```ruby
#!/usr/bin/env ruby
File.open('tags', 'w') do |tags|
  Dir["**/*.md"].each do |path|
    base = File.basename(path, '.md')
    tags.puts "#{base}\t#{path}\t1;\"\tF"
  end
end
```

Note: this tags file is different than running `ctags --extras=f **/*.md` because it strips the file extension from the tag in order to align with the internal link notation.

```vim
function! CursorTagJump() abort
  let link = vimsidian#unit#CursorLink()
  execute 'tag' link
endfunction
command! VimsidianTagJump call CursorTagJump()
```

```vim
augroup vimsidian_augroup
  au!
  au BufNewFile,BufReadPost $VIMSIDIAN_PATH_PATTERN nn <buffer> <C-]> :VimsidianTagJump<CR>
augroup END
```

This feeds the current cursor's internal link into ctags so you can use ctrl-] to jump in as many times as you like, then use ctrl-t to jump back out all the way back to the beginning!

Now I realized I've hacked this all together. This is in fact my first vim function. However, the ability to jump in and out like this feels pretty great! I'm not sure if there is a better way to implement this kind of behavior. Perhaps using the tags stack is not required, perhaps vimsidian could keeps its own little array/stack of the locations jumped to so it could provide the jump back out capability.

**Comment by kis9a** [comment]
@andynu 

Thanks for the good idea ! 
That feature was needed for me as well, I have created the following PR.  <https://github.com/kis9a/vimsidian/pull/10>
Could you please verify or review it for me so I can merge it?

Any improvements or advice, please comment.
If you have any questions about the details, please ask!
